global:
  scrape_interval: 4s
  scrape_timeout: 4s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "nitro"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets:
        - host.docker.internal:6070
        labels:
          instance: local_node
