version: "3.9"
services:
  validator:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:8247:8547"
      - "127.0.0.1:8248:8548"
    volumes:
      - "validator-data:/home/user/.arbitrum/local/nitro"
      - "config:/config"
      - type: bind
        source: ./val_jwt.hex
        target: /config/val_jwt.hex
      - type: bind
        source: ./validator_config.json
        target: /config/validator_config.json
      - type: bind
        source: ./l2_chain_info.json
        target: /config/l2_chain_info.json
    command: --conf.file /config/validator_config.json --http.port 8547 --http.api net,web3,arb,debug --ws.port 8548
    depends_on:
      - validation_node

  validation_node:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:8949:8549"
    volumes:
      - "config:/config"
      - type: bind
        source: ./val_jwt.hex
        target: /config/val_jwt.hex
      - type: bind
        source: ./validation_node_config.json
        target: /config/validation_node_config.json
      - type: bind
        source: ./l2_chain_info.json
        target: /config/l2_chain_info.json
    command: --conf.file /config/validation_node_config.json
    entrypoint: /usr/local/bin/nitro-val

volumes:
  validator-data:
  config:
